# Generated by Django 3.2.9 on 2022-01-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relations',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
