# Generated by Django 3.2.9 on 2022-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relations',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='users.Profile'),
        ),
    ]
