# Generated by Django 3.2.9 on 2022-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0006_auto_20220129_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tweet',
        ),
        migrations.AddField(
            model_name='feed',
            name='tweet',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post'),
        ),
    ]
