# Generated by Django 3.2.9 on 2022-01-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0007_auto_20220129_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='retweeted_feed',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
