# Generated by Django 3.2.9 on 2022-01-29 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0008_auto_20220129_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_feed',
            field=models.ManyToManyField(blank=True, related_name='feeds_like', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_tweet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='retweeted_feed',
            field=models.ManyToManyField(blank=True, related_name='feeds_retweet', to='blog.Post'),
        ),
    ]
