# Generated by Django 3.2.9 on 2022-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0009_auto_20220129_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='liked_feed',
            new_name='following_likes',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='retweeted_feed',
            new_name='following_retweets',
        ),
        migrations.AddField(
            model_name='profile',
            name='following_tweets',
            field=models.ManyToManyField(blank=True, related_name='feeds_tweet', to='blog.Post'),
        ),
    ]
