# Generated by Django 3.2.9 on 2022-01-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0010_auto_20220130_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following_likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_retweets',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_tweets',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pinned_tweet',
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_likes', models.ManyToManyField(blank=True, related_name='feeds_like', to='blog.Post')),
                ('following_retweets', models.ManyToManyField(blank=True, related_name='feeds_retweet', to='blog.Post')),
                ('following_tweets', models.ManyToManyField(blank=True, related_name='feeds_tweet', to='blog.Post')),
                ('pinned_tweet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_profile', to='users.profile')),
            ],
        ),
    ]
