# Generated by Django 3.2.9 on 2022-01-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0011_auto_20220130_0251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feed',
            new_name='HomeFeed',
        ),
    ]
