# Generated by Django 3.2.9 on 2022-02-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
        ('users', '0014_auto_20220203_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homefeed',
            name='my_likes',
        ),
        migrations.RemoveField(
            model_name='homefeed',
            name='my_retweets',
        ),
        migrations.RemoveField(
            model_name='homefeed',
            name='pinned_tweet',
        ),
        migrations.RemoveField(
            model_name='profilefeed',
            name='following_likes',
        ),
        migrations.RemoveField(
            model_name='profilefeed',
            name='following_retweets',
        ),
        migrations.RemoveField(
            model_name='profilefeed',
            name='following_tweets',
        ),
        migrations.AddField(
            model_name='homefeed',
            name='following_likes',
            field=models.ManyToManyField(blank=True, related_name='profile_feeds_like', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='homefeed',
            name='following_retweets',
            field=models.ManyToManyField(blank=True, related_name='profile_feeds_retweet', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='homefeed',
            name='following_tweets',
            field=models.ManyToManyField(blank=True, related_name='profile_feeds_tweet', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='profilefeed',
            name='my_likes',
            field=models.ManyToManyField(blank=True, related_name='home_feeds_like', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='profilefeed',
            name='my_retweets',
            field=models.ManyToManyField(blank=True, related_name='home_feeds_retweet', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='profilefeed',
            name='pinned_tweet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
