# Generated by Django 3.2.9 on 2022-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
        ('users', '0015_auto_20220204_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefeed',
            name='following_likes',
            field=models.ManyToManyField(blank=True, related_name='home_feeds_like', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='homefeed',
            name='following_retweets',
            field=models.ManyToManyField(blank=True, related_name='home_feeds_retweet', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='homefeed',
            name='following_tweets',
            field=models.ManyToManyField(blank=True, related_name='home_feeds_tweet', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='profilefeed',
            name='my_likes',
            field=models.ManyToManyField(blank=True, related_name='profile_feeds_like', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='profilefeed',
            name='my_retweets',
            field=models.ManyToManyField(blank=True, related_name='profile_feeds_retweet', to='blog.Post'),
        ),
    ]
