# Generated by Django 3.2.9 on 2022-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220209_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeed',
            old_name='my_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='profilefeed',
            old_name='my_retweets',
            new_name='retweets',
        ),
    ]
