# Generated by Django 3.2.9 on 2022-02-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220209_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeed',
            old_name='likes',
            new_name='liked',
        ),
        migrations.RenameField(
            model_name='profilefeed',
            old_name='retweets',
            new_name='retweeted',
        ),
    ]
