# Generated by Django 3.2.9 on 2022-01-26 10:59

import blog.models
import blog.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=180, null=True, verbose_name='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_comments', models.IntegerField(default=0)),
                ('num_retweets', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
                ('media', models.FileField(blank=True, null=True, upload_to=blog.models.post_media_path, validators=[blog.validators.validate_file_type], verbose_name='')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
